export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CART = "LOAD_CART";
export const CHANGE_QUANTITY_OF_CARTITEM = "CHANGE_QUANTITY_OF_CARTITEM";
// export const UPDATE_CART = "UPDATE_CART";